/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.reges.contatos.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 * SERVER HSQL: java -cp hsqldb.jar org.hsqldb.server.Server --database.0 file:agenda --dbname.0 agenda
 * GERENCIADOR: java -cp hsqldb.jar org.hsqldb.util.DatabaseManager
 * 
 * CREATE TABLE Contatos (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(255), sobrenome VARCHAR(255), categoria VARCHAR(255), apelido VARCHAR(255), tipo_contato VARCHAR(255));
 * CREATE TABLE Emails (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, endereco_email VARCHAR(255), principal BIT, id_contato INTEGER);
 * 
 * 
 * @author lucas
 */
public class Database {
    
    static Connection getConnection() throws SQLException{
        return DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/agenda", "sa", "");
    }
    
}
